-- Initial migration: creates the base users table.
-- Additional tables (sessions, tokens, domain tables, etc.) are generated by
-- subsequent migrations produced by `drizzle-kit generate`.
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY);
